# buildJava.yml

name: "Java CI with Maven - Test and package"

# Ce workflow s'exécute lors d'une pull request vers la branche main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # Utilisation de la dernière version d'Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du dépôt courant
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3 : Construction et test avec Maven
      - name: Build and Test with Maven
        run: mvn -B package